### PR TITLE
Auto deploy

### PR DESCRIPTION
**Pull request by zoepage**

### CODE REVIEW

**Comment by gr2m** [comment]
- [ ] rebase on `gh-pages`

**Comment by zoepage** [comment]
After gr2m/initials#17 is approved, I'll add the tasks to this PR.

**Comment by zoepage** [comment]
@gr2m could you please check, if the PR is good like that? :)

**Comment by gr2m** [comment]
looking all great, just made few adjustments, see the last commits.
Merged via 1d0e41d

**Pull request closed without merging**
