### PR TITLE
Added patterns for parsing fractional seconds properly.

### PR DESCRIPTION
**Pull request by mgd134**
I added some tests as well. Let me know if you'd like me to do anything else. Thanks again for all the work on this project.

### CODE REVIEW

**Comment by mgd134** [comment]
I see the build failed. I experienced this as well. I removed the dependency `"bootstrap-editable-table": "https://github.com/gr2m/bootstrap-editable-table#gh-pages",` and I was able to run the tests. That project does not appear to define a version in its package.json which I think may be the problem. If not please point me in the right direction to fix it and I'll do so. Thanks.

**Comment by gr2m** [comment]
the failing build is not your fault, I'm fixing it right now, please give me a moment. Sorry for the trouble :)

**Comment by gr2m** [comment]
okay, merged via 11d16da. I reworded your commit message so [semantic-release](https://github.com/semantic-release/semantic-release) understands it. If build passes it will release a new patch version in a moment

**Comment by gr2m** [comment]
Released as [1.1.4](https://github.com/gr2m/moment-parseformat/releases/tag/v1.1.4)

Thanks a lot, that was great work @mgd134 :bouquet:

**Comment by mgd134** [comment]
Thanks! No problem.

**Pull request closed without merging**
