### PR TITLE
Add support for Number as input for parseFormat

### PR DESCRIPTION
**Pull request by idanb11**
Added needed test.

### CODE REVIEW

**Comment by gr2m** [comment]
your test is failing, it needs some implementation, are you still on it?

**Comment by idanb11** [comment]
I don't know, 
It doesn't fail on my side:

```
$ node test/moment-parseformat-test.js
TAP version 13
# standard cases
ok 1 Thursday 9:20pm ΓåÆ dddd h:mma
ok 2 Thursday, February 6th, 2014 9:20pm ΓåÆ dddd, MMMM Do, YYYY h:mma
ok 3 23:20 ΓåÆ H:mm
ok 4 02/03/14 ΓåÆ MM/DD/YY
ok 5 2014-01-10 20:00:15 ΓåÆ YYYY-MM-DD H:mm:ss
ok 6 Thursday at 9:20pm ΓåÆ dddd [at] h:mma
ok 7 1397418578 ΓåÆ X
# GitHub issues
ok 8 #3 Thursday, February 6th, 2014 9:20pm -> dddd, MMMM Do, YYYY h:mma
ok 9 #3 sanity check: "Thursday, February 6th, 2014 9:20pm" parses 6th correctly
ok 10 #4 1.1.2010 ΓåÆ D.M.YYYY
ok 11 #11 9-17-1980 ΓåÆ M-D-YYYY
ok 12 #5 2014-02-02T10:11:58+00:00 ΓåÆ YYYY-MM-DDTHH:mm:ssZ
ok 13 #5 August 26, 2014 02:30pm ΓåÆ MMMM D, YYYY hh:mma
ok 14 #5 August 06, 2014 ΓåÆ MMMM DD, YYYY
ok 15 #12 3-1-81 ΓåÆ D-M-YY
ok 16 #15 01-01-2015 ΓåÆ DD-MM-YYYY
ok 17 #15 01-01-2015 (preferredOrder: MDY) ΓåÆ MM-DD-YYYY
ok 18 #20 10/8/2014 5:08:35 PM ΓåÆ M/D/YYYY h:mm:ss A
ok 19 #20 10/8/2014 5:08:35 am ΓåÆ M/D/YYYY h:mm:ssa
ok 20 #23 2014-23-04T01:20:28.888+02:00 ΓåÆ YYYY-MM-DDTHH:mm:ss.SSSZ
ok 21 #23 2014-09-04T01:20:28.888+02:00 ΓåÆ YYYY-MM-DDTHH:mm:ss.SSSZ
ok 22 #23 2014-09-04T01:20:28.888-02:00 ΓåÆ YYYY-MM-DDTHH:mm:ss.SSSZ
ok 23 #23 2014-02-02T10:11:58.888Z ΓåÆ YYYY-MM-DDTHH:mm:ss.SSSZ
ok 24 1434575583 ΓåÆ X
ok 25 1318781876406 ΓåÆ x
ok 26 October 27 2015 11:28:32.0 ΓåÆ MMMM D YYYY HH:mm:ss.S
ok 27 October 27 2015 11:28:32.0 ΓåÆ MMMM D YYYY HH:mm:ss.SS
ok 28 October 27 2015 11:28:32.0 ΓåÆ MMMM D YYYY HH:mm:ss.SSS
ok 29 Feb 1 2016 1:03:22.111 ΓåÆ MMM D YYYY H:mm:ss.SSS
ok 30 Feb 1 2016 1:03:22.111 ΓåÆ MMM D YYYY H:mm:ss.SS
ok 31 Feb 1 2016 1:03:22.111 ΓåÆ MMM D YYYY H:mm:ss.S
ok 32 #56 2014-23-04T01:20:28.888+0200 ΓåÆ YYYY-MM-DDTHH:mm:ss.SSSZ
ok 33 #56 2014-09-04T01:20:28.888+0200 ΓåÆ YYYY-MM-DDTHH:mm:ss.SSSZ
ok 34 #56 2014-09-04T01:20:28.888-0200 ΓåÆ YYYY-MM-DDTHH:mm:ss.SSSZ
ok 35 #56 2014-09-04T01:20:28+0200 ΓåÆ YYYY-MM-DDTHH:mm:ssZ
# GitHub issues - special cases
ok 36 last number is > 12 - 3/15 ΓåÆ M/Y
ok 37 last number is > 12 - 03/15 ΓåÆ MM/Y
ok 38 last number is > 12 - 11/15 ΓåÆ MM/Y
ok 39 first number is > 12 - 15/3 ΓåÆ DD/M
ok 40 both numbers are < 13 - 03/12 ΓåÆ DD/MM
ok 41 both numbers are < 13 - 3/3 ΓåÆ D/M
ok 42 first number is > 12 && <= 31 - 13/2 ΓåÆ DD/M
ok 43 both numbers are < 13 - 03/12 ΓåÆ DD/MM
ok 44 both numbers are < 13 - 03/03 ΓåÆ DD/MM
ok 45 first number is > 12 && <= 31 - 13/02 ΓåÆ DD/MM
ok 46 both numbers are < 13 - 3/12 ΓåÆ D/MM
ok 47 February 6th, 2014 9.20 ΓåÆ MMMM Do, YYYY h.mm
ok 48 2.2.2014 09.20 ΓåÆ D.M.YYYY H.mm
ok 49 2.2.2014 11.20 ΓåÆ D.M.YYYY H.mm
ok 50 2.2.2014 9.02 ΓåÆ D.M.YYYY h.mm
# Github issue #40
ok 51 31/12/2013 ΓåÆ DD/MM/YYYY
ok 52 12/31/2013 ΓåÆ MM/DD/YYYY
ok 53 31-12-2013 ΓåÆ DD-MM-YYYY
ok 54 12-31-2013 ΓåÆ MM-DD-YYYY

1..54
# tests 54
# pass  54

# ok

```

I added test No. 7

**Comment by idanb11** [comment]
This is what fails:

```
> moment-parseformat@ pretest /home/travis/build/gr2m/moment-parseformat
> standard
standard: Use JavaScript Standard Style (http://standardjs.com)
  /home/travis/build/gr2m/moment-parseformat/lib/parseformat.js:20:31: Unnecessary escape character: \/.
  /home/travis/build/gr2m/moment-parseformat/lib/parseformat.js:20:33: Unnecessary escape character: \..
  /home/travis/build/gr2m/moment-parseformat/lib/parseformat.js:20:35: Unnecessary escape character: \-.
  /home/travis/build/gr2m/moment-parseformat/lib/parseformat.js:20:49: Unnecessary escape character: \/.
  /home/travis/build/gr2m/moment-parseformat/lib/parseformat.js:20:51: Unnecessary escape character: \..
  /home/travis/build/gr2m/moment-parseformat/lib/parseformat.js:20:53: Unnecessary escape character: \-.
  /home/travis/build/gr2m/moment-parseformat/lib/parseformat.js:22:27: Unnecessary escape character: \-.
  /home/travis/build/gr2m/moment-parseformat/lib/parseformat.js:57:30: Unnecessary escape character: \/.
  /home/travis/build/gr2m/moment-parseformat/lib/parseformat.js:57:41: Unnecessary escape character: \/.
npm ERR! Test failed.  See above for more details.
```

**Comment by gr2m** [comment]
Okay cheers, I got it

**Pull request merged**
